version: "3.9"
services:
  cloud-api:
    image: tek/cloud-api:1.0
    container_name: "cloud-api"
    networks:
      - infra-network

  nginx-infra:
    image: tek/nginx-infra:1.0
    container_name: "nginx-infra"
    networks:
      - infra-network
    ports:
      - ${API_PORT}:80

networks:
  infra-network:
    driver: bridge